name: flutter_permissions_helper
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

flutter:
  plugin:
    androidPackage: com.andrewackerman.flutterpermissionshelper
    pluginClass: FlutterPermissionsHelperPlugin
